import { useState, useEffect } from 'react';
import { createClient } from '@supabase/supabase-js';

// ── Injected at build time via VITE_ env vars ──
const SUPA_URL = import.meta.env.VITE_SUPABASE_URL || '';
const SUPA_KEY = import.meta.env.VITE_SUPABASE_KEY || '';
const sb = createClient(SUPA_URL, SUPA_KEY);

const M = "'SF Mono','JetBrains Mono','Fira Code',monospace";
const C = {bg:"#08080c",c1:"#0e0e14",c2:"#15151e",br:"#1c1c2a",t1:"#eeeef2",t2:"#8e8e9a",t3:"#4e4e5a",acc:"#f59e0b",red:"#ef4444",grn:"#22c55e",blu:"#3b82f6",pur:"#a78bfa",grad:"linear-gradient(135deg,#f59e0b,#ef4444,#ec4899)"};
const FLAGS={in:"🇮🇳",gb:"🇬🇧",de:"🇩🇪",fr:"🇫🇷",us:"🇺🇸",ca:"🇨🇦",au:"🇦🇺",ie:"🇮🇪",remote:"🌍",other:"🌐"};
const CATS=["All","SRE","Platform","Security","DevSecOps","DevOps","Cloud","Infrastructure","Backend","Frontend","Fullstack","Data","ML/AI","Mobile","QA","Product","Architect"];
const QUICK=["Site Reliability Engineer","Platform Engineer","Cloud Security","DevSecOps","DevOps","Infrastructure"];

// ── Global styles ──
const globalCSS = `
::-webkit-scrollbar{width:5px}::-webkit-scrollbar-track{background:#08080c}::-webkit-scrollbar-thumb{background:#1c1c2a;border-radius:3px}
::selection{background:rgba(245,158,11,.2);color:#f59e0b}
@keyframes up{from{opacity:0;transform:translateY(14px)}to{opacity:1;transform:translateY(0)}}
@keyframes scan{0%{transform:translateX(-100%)}100%{transform:translateX(100%)}}
@keyframes fadeIn{from{opacity:0}to{opacity:1}}
@keyframes pulse{0%,100%{opacity:.5}50%{opacity:1}}
@keyframes spin{to{transform:rotate(360deg)}}
input,textarea,select{font-family:inherit;color:#eeeef2;background:#0e0e14;border:1px solid #1c1c2a;border-radius:8px;padding:10px 14px;font-size:14px;outline:none;width:100%;box-sizing:border-box;caret-color:#f59e0b}
input::placeholder,textarea::placeholder{color:#4e4e5a}
input:focus,textarea:focus{border-color:rgba(245,158,11,.3)}
a{color:#3b82f6;text-decoration:none}
`;

// ── DB helpers ──
const edge = async (fn, body) => { try { const r = await fetch(`${SUPA_URL}/functions/v1/${fn}`, { method:"POST", headers:{Authorization:`Bearer ${SUPA_KEY}`,"Content-Type":"application/json"}, body:JSON.stringify(body) }); return r.ok ? r.json() : null; } catch { return null; } };

const db = {
  async getJobs(s,cat,lim=80){let q=sb.from("jobs").select("*").order("posted",{ascending:false}).limit(lim);if(s)q=q.or(`title.ilike.%${s}%,company.ilike.%${s}%`);if(cat&&cat!=="All")q=q.eq("category",cat);const{data}=await q;return data||[];},
  async getProfile(){const{data:{user}}=await sb.auth.getUser();if(!user)return null;const{data}=await sb.from("profiles").select("*").eq("id",user.id).single();return data;},
  async saveProfile(p){const{data:{user}}=await sb.auth.getUser();if(!user)return;await sb.from("profiles").upsert({id:user.id,...p,updated_at:new Date().toISOString()});},
  async getQA(){const{data}=await sb.from("saved_qa").select("*").order("created_at");return data||[];},
  async addQA(q,a){const{data:{user}}=await sb.auth.getUser();if(!user)return;await sb.from("saved_qa").insert({user_id:user.id,question:q,answer:a});},
  async deleteQA(id){await sb.from("saved_qa").delete().eq("id",id);},
  async getApps(){const{data}=await sb.from("applications").select("*").order("applied_at",{ascending:false});return data||[];},
  async uploadResume(file){const{data:{user}}=await sb.auth.getUser();if(!user||!file)return null;const fp=`${user.id}/${file.name}`;await sb.storage.from("resumes").upload(fp,file,{upsert:true});const{data:u}=sb.storage.from("resumes").getPublicUrl(fp);await sb.from("profiles").update({resume_url:u.publicUrl}).eq("id",user.id);return u.publicUrl;},
  async queueApply(job,cover){const{data:{user}}=await sb.auth.getUser();if(!user)return;const p=await this.getProfile();const m=(job.url||"").match(/greenhouse\.io\/(\w+)\/jobs\/(\d+)/);await sb.from("apply_queue").insert({user_id:user.id,job_id:job.id,job_title:job.title,company:job.company,job_url:job.url,source:job.source,board_slug:m?.[1],gh_job_id:m?.[2],cover_letter:cover,resume_url:p?.resume_url,status:"pending"});},
  scrapeForm: (url,src) => edge("scrape-form",{url,source:src}),
  triggerApply: () => edge("trigger-apply",{}),
  callAI: body => edge("ai",body),
  liveSearch: q => edge("search-jobs",{query:q}),
};

// ── Small components ──
function Chip({active,color=C.acc,children,onClick}){return <button onClick={onClick} style={{padding:"5px 14px",fontSize:12,border:`1px solid ${active?color+"55":C.br}`,borderRadius:99,background:active?color+"15":"transparent",color:active?color:C.t3,cursor:"pointer",fontWeight:500,fontFamily:M,transition:"all .15s"}}>{children}</button>}
function ScanBar(){return <div style={{height:2,background:C.c2,borderRadius:1,overflow:"hidden",margin:"10px 0"}}><div style={{height:"100%",width:"30%",background:C.grad,animation:"scan 1.4s ease infinite"}}/></div>}
function Modal({children,onClose}){return <div style={{position:"fixed",inset:0,background:"rgba(0,0,0,.8)",backdropFilter:"blur(12px)",zIndex:200,display:"flex",alignItems:"center",justifyContent:"center",padding:16,animation:"fadeIn .2s"}} onClick={e=>e.target===e.currentTarget&&onClose()}><div style={{background:C.c1,border:`1px solid ${C.br}`,borderRadius:20,maxWidth:560,width:"100%",maxHeight:"88vh",overflow:"auto",padding:28,animation:"up .3s ease"}}>{children}</div></div>}

// ── Landing Page ──
function Landing({onLogin}){return(
  <div style={{minHeight:"100vh",background:C.bg}}>
    <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"16px 24px",maxWidth:960,margin:"0 auto"}}><div style={{display:"flex",alignItems:"center",gap:10}}><span style={{fontSize:24}}>🔥</span><span style={{fontSize:20,fontWeight:900,background:C.grad,WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent"}}>FLINT</span></div><div style={{display:"flex",gap:8}}><a href="https://github.com/mafiaguy/flint" target="_blank" rel="noreferrer" style={{padding:"8px 16px",border:`1px solid ${C.br}`,borderRadius:8,color:C.t2,fontSize:13}}>GitHub ↗</a><button onClick={onLogin} style={{padding:"8px 20px",background:C.grad,color:"#fff",border:"none",borderRadius:8,fontSize:13,fontWeight:700,cursor:"pointer"}}>Sign In</button></div></div>
    <div style={{maxWidth:720,margin:"0 auto",padding:"80px 24px 60px",textAlign:"center"}}><div style={{display:"inline-block",padding:"6px 16px",border:`1px solid ${C.acc}33`,borderRadius:99,fontSize:12,color:C.acc,fontFamily:M,marginBottom:20}}>OPEN SOURCE · FREE FOREVER · 9 JOB SOURCES</div><h1 style={{fontSize:"clamp(36px,6vw,56px)",fontWeight:900,lineHeight:1.1,marginBottom:20}}><span style={{background:C.grad,WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent"}}>Stop hunting.</span><br/><span style={{color:C.t1}}>Start finding.</span></h1><p style={{fontSize:18,color:C.t2,maxWidth:520,margin:"0 auto 36px",lineHeight:1.7}}>Jobs scraped fresh from LinkedIn, Greenhouse, Lever, Adzuna & 5 more. AI matching. Auto apply. Zero config.</p><button onClick={onLogin} style={{padding:"16px 40px",background:C.grad,color:"#fff",border:"none",borderRadius:12,fontSize:17,fontWeight:800,cursor:"pointer"}}>Get Started — Free</button><p style={{color:C.t3,fontSize:12,marginTop:12}}>No credit card. No API keys. Just sign in.</p></div>
    <div style={{display:"flex",justifyContent:"center",gap:12,flexWrap:"wrap",padding:"0 24px 60px",maxWidth:680,margin:"0 auto"}}>{["LinkedIn","Adzuna","Greenhouse","Lever","Ashby","Workable","HackerNews","Naukri"].map(s=><span key={s} style={{padding:"6px 16px",border:`1px solid ${C.br}`,borderRadius:99,fontSize:12,color:C.t2,fontFamily:M}}>{s}</span>)}</div>
    <div style={{maxWidth:820,margin:"0 auto",padding:"0 24px 80px",display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:16}}>{[{i:"🔍",t:"Real jobs",d:"9 sources, 50+ boards, every 8 hours."},{i:"⚡",t:"AI matching",d:"Llama 3.3 70B scores every job."},{i:"🚀",t:"Auto Apply",d:"Playwright fills forms and submits."},{i:"📋",t:"Smart Q&A",d:"Real fields auto-detected and filled."},{i:"🔒",t:"Private",d:"Google/GitHub login. RLS-scoped data."},{i:"💰",t:"$0/month",d:"All free tiers. MIT license."}].map((f,i)=><div key={i} style={{background:C.c1,border:`1px solid ${C.br}`,borderRadius:16,padding:20,animation:`up .4s ease ${i*.06}s both`}}><span style={{fontSize:28,display:"block",marginBottom:10}}>{f.i}</span><h3 style={{fontSize:15,fontWeight:700,color:C.t1,marginBottom:6}}>{f.t}</h3><p style={{fontSize:13,color:C.t2,lineHeight:1.6}}>{f.d}</p></div>)}</div>
    <div style={{textAlign:"center",padding:"40px 24px 60px",borderTop:`1px solid ${C.br}`}}><button onClick={onLogin} style={{padding:"14px 36px",background:C.grad,color:"#fff",border:"none",borderRadius:12,fontSize:16,fontWeight:700,cursor:"pointer"}}>Launch FLINT 🔥</button></div>
    <div style={{textAlign:"center",padding:"20px 24px",borderTop:`1px solid ${C.br}`,fontSize:12,color:C.t3}}>Built by <a href="https://mafiaguy.github.io" target="_blank" rel="noreferrer" style={{color:C.acc}}>mafiaguy</a> · <a href="https://github.com/mafiaguy/flint" target="_blank" rel="noreferrer" style={{color:C.t2}}>Source</a> · MIT</div>
  </div>
)}

// ── Auth ──
function AuthModal({onClose}){const[ld,setLd]=useState(null);const go=async p=>{setLd(p);await sb.auth.signInWithOAuth({provider:p,options:{redirectTo:window.location.origin+window.location.pathname}});};return <Modal onClose={onClose}><div style={{textAlign:"center",padding:"10px 0"}}><span style={{fontSize:40}}>🔥</span><h2 style={{fontSize:24,fontWeight:800,color:C.t1,margin:"12px 0 4px"}}>Sign in to FLINT</h2><p style={{color:C.t2,fontSize:14,marginBottom:28}}>Your data stays private.</p><button onClick={()=>go("google")} disabled={!!ld} style={{width:"100%",padding:14,background:"#fff",color:"#333",border:"none",borderRadius:10,fontSize:15,fontWeight:600,cursor:ld?"wait":"pointer",marginBottom:10}}>Continue with Google</button><button onClick={()=>go("github")} disabled={!!ld} style={{width:"100%",padding:14,background:C.c2,color:C.t1,border:`1px solid ${C.br}`,borderRadius:10,fontSize:15,fontWeight:600,cursor:ld?"wait":"pointer"}}>Continue with GitHub</button></div></Modal>}

// ── Job Card ──
function JobCard({job,applied,onApply,onMatch}){const[exp,setExp]=useState(false);const days=job.posted?Math.max(0,Math.floor((Date.now()-new Date(job.posted))/864e5)):null;const srcC=job.source==="LinkedIn"?"#0a66c2":job.source==="Greenhouse"?"#3b8132":job.source==="HackerNews"?"#ff6600":C.acc;return(
  <div style={{background:C.c1,border:`1px solid ${applied?C.grn+"33":C.br}`,borderRadius:16,padding:18,animation:"up .35s ease",position:"relative"}}>
    {applied&&<div style={{position:"absolute",top:12,right:12,background:C.grn+"22",color:C.grn,fontSize:10,fontWeight:800,padding:"3px 10px",borderRadius:99,fontFamily:M}}>APPLIED</div>}
    <div style={{display:"flex",gap:14}}><div style={{width:44,height:44,borderRadius:12,background:srcC+"15",border:`1px solid ${srcC}33`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:18,fontWeight:900,color:srcC,flexShrink:0,fontFamily:M}}>{job.company?.charAt(0)||"?"}</div><div style={{flex:1,minWidth:0}}><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap",marginBottom:5}}><span style={{fontSize:10,fontFamily:M,fontWeight:700,color:srcC}}>{(job.source||"").toUpperCase()}</span><span style={{fontSize:11,color:C.t3}}>{FLAGS[job.country]||"🌐"}</span>{job.remote&&<span style={{fontSize:10,color:C.grn,fontFamily:M}}>🌍 Remote</span>}{days!==null&&<span style={{fontSize:10,color:C.t3,fontFamily:M}}>⏱ {days===0?"Today":`${days}d`}</span>}</div><h3 style={{margin:"0 0 4px",fontSize:16,fontWeight:700,color:C.t1,lineHeight:1.3}}>{job.title}</h3><p style={{margin:0,fontSize:14,color:C.t2}}>{job.company}</p><p style={{margin:"2px 0 0",fontSize:12,color:C.t3}}>{job.location}</p>{job.salary&&job.salary!=="—"&&<p style={{margin:"6px 0 0",fontSize:14,fontWeight:700,color:C.grn,fontFamily:M}}>{job.salary}</p>}</div></div>
    {exp&&<div style={{marginTop:14,padding:14,background:C.bg,borderRadius:10,border:`1px solid ${C.br}`,fontSize:13,lineHeight:1.7,color:C.t2,maxHeight:400,overflow:"auto",whiteSpace:"pre-wrap"}}>{job.description||"No description."}</div>}
    <div style={{display:"flex",gap:8,marginTop:14,flexWrap:"wrap",alignItems:"center"}}>{job.category&&<span style={{fontSize:10,fontFamily:M,color:C.t3,background:C.c2,padding:"4px 10px",borderRadius:99}}>{job.category}</span>}<div style={{flex:1}}/><button onClick={()=>setExp(!exp)} style={{padding:"7px 14px",fontSize:12,border:`1px solid ${C.br}`,borderRadius:8,background:"transparent",color:C.t2,cursor:"pointer"}}>{exp?"Hide":"Details"}</button><a href={job.url} target="_blank" rel="noreferrer" style={{padding:"7px 14px",fontSize:12,border:`1px solid ${C.blu}33`,borderRadius:8,color:C.blu}}>Career Page ↗</a><button onClick={()=>onMatch(job)} style={{padding:"7px 14px",fontSize:12,border:`1px solid ${C.pur}33`,borderRadius:8,background:"transparent",color:C.pur,cursor:"pointer",fontWeight:600}}>⚡ Match</button><button onClick={()=>onApply(job)} style={{padding:"8px 20px",background:applied?C.grn+"22":C.grad,color:applied?C.grn:"#fff",border:"none",borderRadius:8,fontSize:12,fontWeight:700,cursor:"pointer"}}>{applied?"✓ Applied":"Apply →"}</button></div>
  </div>
)}

// ── Apply Modal ──
function ApplyModal({job,profile,onClose,onApply}){
  const hasAPI=/greenhouse|lever|ashby/i.test(job.source||"");
  const[fields,setFields]=useState([]);const[ans,setAns]=useState({});const[loading,setLoading]=useState(hasAPI);
  const[cover,setCover]=useState("");const[genL,setGenL]=useState(false);
  const gen=async()=>{setGenL(true);const r=await db.callAI({type:"cover",job:{title:job.title,company:job.company,desc:(job.description||"").slice(0,600)},profile});setCover(r?.text||"AI unavailable.");setGenL(false);};

  useEffect(()=>{if(!hasAPI)return;(async()=>{setLoading(true);let fd=await db.scrapeForm(job.url,job.source);if(!fd?.fields?.length&&job.questions){try{fd={fields:JSON.parse(job.questions).map(x=>({label:x.label||x.q,type:x.type||"text",required:x.required,options:x.options||[]}))}}catch{}}if(fd?.fields?.length){setFields(fd.fields);const r=await db.callAI({type:"autofill",job:{title:job.title,company:job.company,desc:(job.description||"").slice(0,800)},profile,questions:fd.fields.map(f=>({label:f.label,type:f.type}))});if(r?.text){try{const f=JSON.parse(r.text.replace(/```json|```/g,"").trim());const a={};fd.fields.forEach((fld,i)=>{const m=f.find(x=>(fld.label||"").toLowerCase().includes((x.q||"").toLowerCase().slice(0,12)));a[i]=m?.a||"";});setAns(a);}catch{}}}setLoading(false);})();},[]);

  if(!hasAPI)return <Modal onClose={onClose}><div style={{textAlign:"center",padding:"10px 0"}}><div style={{width:56,height:56,borderRadius:14,background:C.acc+"15",border:`1px solid ${C.acc}33`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:24,fontWeight:900,color:C.acc,margin:"0 auto 16px",fontFamily:M}}>{job.company?.charAt(0)}</div><h3 style={{color:C.t1,fontSize:20,fontWeight:800,margin:"0 0 4px"}}>{job.title}</h3><p style={{color:C.t2,fontSize:14}}>{job.company} · {job.location}</p><p style={{color:C.t3,fontSize:12,margin:"12px 0 24px"}}>Apply directly on {job.company}'s career page.</p><a href={job.url} target="_blank" rel="noreferrer" onClick={()=>{onApply(job,"","manual");onClose();}} style={{display:"block",width:"100%",padding:16,background:C.grad,color:"#fff",borderRadius:12,textAlign:"center",fontWeight:800,fontSize:16,marginBottom:10}}>Apply on {job.company} ↗</a><button onClick={()=>{onApply(job,"","manual");onClose();}} style={{width:"100%",padding:12,background:C.c2,color:C.t2,border:`1px solid ${C.br}`,borderRadius:10,fontSize:13,cursor:"pointer"}}>Just track this</button></div></Modal>;

  return <Modal onClose={onClose}>
    <div style={{display:"flex",justifyContent:"space-between",marginBottom:20}}><div><div style={{fontSize:10,fontFamily:M,letterSpacing:2,color:C.acc,marginBottom:6}}>APPLYING TO</div><h3 style={{color:C.t1,fontSize:20,fontWeight:800,margin:0}}>{job.title}</h3><p style={{color:C.t2,fontSize:13,margin:"4px 0 0"}}>{job.company} · {job.location}</p></div><button onClick={onClose} style={{background:"none",border:"none",color:C.t3,cursor:"pointer",fontSize:20}}>✕</button></div>
    {loading?<div style={{textAlign:"center",padding:"24px 0"}}><div style={{width:28,height:28,border:`3px solid ${C.br}`,borderTopColor:C.grn,borderRadius:"50%",animation:"spin .8s linear infinite",margin:"0 auto"}}/><p style={{color:C.t3,fontSize:13,marginTop:10}}>Fetching real form fields...</p></div>
    :fields.length>0&&<><div style={{fontSize:10,fontFamily:M,letterSpacing:2,marginBottom:10,color:C.grn,display:"flex",alignItems:"center",gap:6}}><span style={{width:6,height:6,borderRadius:99,background:C.grn}}/>REAL FORM FIELDS ({fields.length} from {job.source})</div>{fields.map((q,i)=>{const isR=q.type==="file"||/resume|cv|upload/i.test(q.label||"");return <div key={i} style={{marginBottom:12}}><label style={{fontSize:12,fontWeight:600,color:C.t2,display:"flex",alignItems:"center",gap:6,marginBottom:4}}>{q.label}{q.required&&<span style={{color:C.red,fontSize:10}}>required</span>}<span style={{fontSize:9,fontFamily:M,padding:"1px 6px",borderRadius:99,background:C.grn+"22",color:C.grn}}>real</span></label>{isR?<div style={{padding:"10px 14px",border:`1px solid ${profile?.resume_url?C.grn+"55":C.br}`,borderRadius:8,background:C.c1,fontSize:13}}>{profile?.resume_url?<span style={{color:C.grn}}>✓ {profile.resume_url.split("/").pop()} (Vault)</span>:<span style={{color:C.acc}}>⚠ Upload resume in Vault</span>}</div>:q.type==="select"&&q.options?.length?<select value={ans[i]||""} onChange={e=>setAns(p=>({...p,[i]:e.target.value}))} style={{width:"100%",padding:"10px 14px",border:`1px solid ${C.br}`,borderRadius:8,fontSize:14,background:C.c1,color:C.t1}}><option value="">Select...</option>{q.options.map(o=><option key={o.label||o} value={o.value||o.label||o}>{o.label||o}</option>)}</select>:<div style={{position:"relative"}}><input value={ans[i]||""} onChange={e=>setAns(p=>({...p,[i]:e.target.value}))}/>{ans[i]&&<span style={{position:"absolute",right:10,top:"50%",transform:"translateY(-50%)",fontSize:9,fontFamily:M,color:C.pur,background:C.pur+"15",padding:"2px 6px",borderRadius:4}}>AI</span>}</div>}</div>})}</>}
    <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",margin:"16px 0 8px"}}><span style={{fontSize:10,fontFamily:M,letterSpacing:2,color:C.t3}}>AI COVER LETTER</span><button onClick={gen} disabled={genL} style={{padding:"6px 16px",background:"transparent",border:`1px solid ${C.pur}55`,borderRadius:8,color:C.pur,cursor:genL?"wait":"pointer",fontSize:12,fontWeight:600}}>⚡ {genL?"...":"Generate"}</button></div>
    <textarea value={cover} onChange={e=>setCover(e.target.value)} placeholder="Click Generate or write..." rows={4} style={{resize:"vertical",lineHeight:1.6}}/>
    <div style={{display:"flex",gap:10,marginTop:20,flexWrap:"wrap"}}><a href={job.url} target="_blank" rel="noreferrer" style={{padding:14,background:C.c2,color:C.t1,borderRadius:12,textAlign:"center",fontWeight:700,fontSize:13,border:`1px solid ${C.br}`,flex:"1 1 100%",display:"block"}}>Open on {job.source} ↗</a><button onClick={()=>{onApply(job,cover,"manual");onClose();}} style={{flex:1,padding:14,background:C.c2,color:C.t1,border:`1px solid ${C.br}`,borderRadius:12,fontWeight:700,fontSize:13,cursor:"pointer"}}>📋 Track</button><button onClick={async()=>{onApply(job,cover,"auto");await db.triggerApply();onClose();}} style={{flex:1,padding:14,background:C.grad,color:"#fff",border:"none",borderRadius:12,fontWeight:800,fontSize:13,cursor:"pointer"}}>🚀 Auto Apply</button></div>
    {!profile?.resume_url&&<p style={{fontSize:11,color:C.acc,marginTop:8,textAlign:"center"}}>⚠ Upload resume in Vault for auto-apply</p>}
  </Modal>;
}

// ── Match Modal ──
function MatchModal({job,profile,onClose}){const[res,setRes]=useState("");const[ld,setLd]=useState(true);useEffect(()=>{(async()=>{const r=await db.callAI({type:"match",job:{title:job.title,company:job.company,location:job.location,desc:(job.description||"").slice(0,800)},profile});setRes(r?.text||"AI unavailable.");setLd(false);})();},[]);return <Modal onClose={onClose}><div style={{display:"flex",justifyContent:"space-between",marginBottom:16}}><div><div style={{fontSize:10,fontFamily:M,letterSpacing:2,color:C.pur,marginBottom:6}}>AI MATCH</div><h3 style={{color:C.t1,fontSize:16,fontWeight:700,margin:0}}>{job.title} · {job.company}</h3></div><button onClick={onClose} style={{background:"none",border:"none",color:C.t3,cursor:"pointer",fontSize:20}}>✕</button></div>{ld?<div style={{textAlign:"center",padding:40}}><div style={{width:36,height:36,border:`3px solid ${C.br}`,borderTopColor:C.acc,borderRadius:"50%",animation:"spin .8s linear infinite",margin:"0 auto"}}/></div>:<div style={{whiteSpace:"pre-wrap",fontSize:13,lineHeight:1.8,color:C.t2,background:C.bg,padding:18,borderRadius:12,border:`1px solid ${C.br}`}}>{res}</div>}</Modal>}

// ═══════════════ MAIN APP ═══════════════
export default function App(){
  const[user,setUser]=useState(undefined);const[showAuth,setShowAuth]=useState(false);
  const[profile,setProfile]=useState(null);const[qa,setQA]=useState([]);
  const[tab,setTab]=useState("hunt");const[jobs,setJobs]=useState([]);const[loading,setLoading]=useState(false);
  const[search,setSearch]=useState("");const[cat,setCat]=useState("All");
  const[selCountries,setSelCountries]=useState([]);const[remoteOnly,setRemoteOnly]=useState(false);
  const[applied,setApplied]=useState([]);const[appliedJobs,setAppliedJobs]=useState([]);
  const[applyM,setApplyM]=useState(null);const[matchM,setMatchM]=useState(null);
  const[status,setStatus]=useState("");const[showMenu,setShowMenu]=useState(false);
  const[aiQ,setAiQ]=useState("");const[aiR,setAiR]=useState("");const[aiLd,setAiLd]=useState(false);
  const[onboarding,setOnboarding]=useState(false);
  const[form,setForm]=useState({role:"",experience:"",skills:"",notice:"",compensation:"",expected:"",visa:"",work_mode:"No Preference"});

  useEffect(()=>{sb.auth.getSession().then(({data:{session}})=>setUser(session?.user||null));const{data:{subscription}}=sb.auth.onAuthStateChange((_,s)=>{setUser(s?.user||null);if(s?.user)loadData();});return()=>subscription.unsubscribe();},[]);
  const loadData=async()=>{const[p,q,apps,j]=await Promise.all([db.getProfile(),db.getQA(),db.getApps(),db.getJobs()]);if(p){setProfile(p);if(!p.role)setOnboarding(true);}setQA(q);setAppliedJobs(apps);setApplied(apps.map(a=>a.job_id));if(j.length){setJobs(j);setStatus(`${j.length} jobs`);}};
  useEffect(()=>{if(user)loadData();},[user]);
  const doSearch=async()=>{setLoading(true);const[c,l]=await Promise.all([db.getJobs(search,cat),db.liveSearch(search)]);const all=[...(c||[]),...(l?.jobs||[])];const seen=new Set();const u=all.filter(j=>{const k=(j.title+j.company).toLowerCase().replace(/\W/g,"");if(seen.has(k))return false;seen.add(k);return true;});u.sort((a,b)=>new Date(b.posted||0)-new Date(a.posted||0));setJobs(u);setStatus(`${u.length} jobs`);setLoading(false);};
  const handleApply=async(job,cover,mode="manual")=>{setApplied(p=>[...new Set([...p,job.id])]);const app={job_id:job.id,title:job.title,company:job.company,location:job.location,source:job.source,url:job.url,cover_letter:cover,status:mode==="auto"?"queued":"applied",applied_at:new Date().toISOString()};setAppliedJobs(p=>[app,...p]);if(mode==="auto")await db.queueApply(job,cover);const{data:{user:u}}=await sb.auth.getUser();if(u)await sb.from("applications").insert({...app,user_id:u.id});};
  const saveSetup=async()=>{await db.saveProfile(form);setProfile(p=>({...p,...form}));for(const[q,a]of[[form.notice&&"Notice period?",form.notice],[form.compensation&&"Current compensation?",form.compensation],[form.expected&&"Expected compensation?",form.expected],[form.visa&&"Work authorization?",form.visa],[form.experience&&"Years of experience?",form.experience+" years"]].filter(([q])=>q))await db.addQA(q,a);setQA(await db.getQA());setOnboarding(false);};
  const filtered=jobs.filter(j=>{const mc=cat==="All"||(j.category||"").toLowerCase().includes(cat.toLowerCase());const ms=!search||[j.title,j.company,j.location].join(" ").toLowerCase().includes(search.toLowerCase());const mr=!remoteOnly||j.remote;const ml=selCountries.length===0||selCountries.includes(j.country);return mc&&ms&&mr&&ml;});

  if(user===undefined)return <div style={{minHeight:"100vh",background:C.bg,display:"flex",alignItems:"center",justifyContent:"center"}}><div style={{width:36,height:36,border:`3px solid ${C.br}`,borderTopColor:C.acc,borderRadius:"50%",animation:"spin .8s linear infinite"}}/></div>;
  if(!user)return <><style>{globalCSS}</style><Landing onLogin={()=>setShowAuth(true)}/>{showAuth&&<AuthModal onClose={()=>setShowAuth(false)}/>}</>;

  if(onboarding)return <div style={{minHeight:"100vh",background:C.bg,display:"flex",alignItems:"center",justifyContent:"center",padding:24}}><style>{globalCSS}</style><div style={{maxWidth:480,width:"100%",animation:"up .4s ease"}}><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:24}}><span style={{fontSize:24}}>🔥</span><span style={{fontSize:18,fontWeight:800,background:C.grad,WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent"}}>FLINT</span></div><h2 style={{color:C.t1,fontSize:24,fontWeight:800,marginBottom:4}}>Welcome{profile?.name?`, ${profile.name.split(" ")[0]}`:""}</h2><p style={{color:C.t3,fontSize:13,marginBottom:24}}>Quick setup — powers AI matching.</p>{[["role","Target role","Senior SRE"],["experience","Years","5"],["skills","Key skills","AWS, K8s, Python"],["notice","Notice period","30 days"],["compensation","Current comp","25 LPA"],["expected","Expected comp","65-90 LPA"],["visa","Work authorization","No visa needed"]].map(([k,l,ph])=><div key={k} style={{marginBottom:12}}><label style={{fontSize:11,fontWeight:600,color:C.t3,fontFamily:M,display:"block",marginBottom:4}}>{l.toUpperCase()}</label><input value={form[k]} onChange={e=>setForm(p=>({...p,[k]:e.target.value}))} placeholder={ph}/></div>)}<label style={{fontSize:11,fontWeight:600,color:C.t3,fontFamily:M,display:"block",marginBottom:6}}>WORK MODE</label><div style={{display:"flex",gap:8,marginBottom:24,flexWrap:"wrap"}}>{["Remote","Hybrid","Onsite","No Preference"].map(m=><Chip key={m} active={form.work_mode===m} onClick={()=>setForm(p=>({...p,work_mode:m}))}>{m}</Chip>)}</div><button onClick={saveSetup} style={{width:"100%",padding:16,background:C.grad,color:"#fff",border:"none",borderRadius:12,fontSize:16,fontWeight:700,cursor:"pointer"}}>Launch FLINT 🔥</button></div></div>;

  const nav=[{id:"hunt",ico:"🔍",l:"Hunt"},{id:"tracked",ico:"📋",l:"Tracked"},{id:"vault",ico:"👤",l:"Vault"},{id:"ai",ico:"⚡",l:"AI Lab"}];
  return <div style={{minHeight:"100vh",background:C.bg}}>
    <style>{globalCSS}</style>
    {/* Header */}
    <div style={{padding:"12px 20px",display:"flex",alignItems:"center",gap:10,borderBottom:`1px solid ${C.br}`}}><span style={{fontSize:20}}>🔥</span><span style={{fontSize:18,fontWeight:900,background:C.grad,WebkitBackgroundClip:"text",WebkitTextFillColor:"transparent"}}>FLINT</span><div style={{flex:1}}/><span style={{width:7,height:7,borderRadius:99,background:C.grn,animation:"pulse 2s infinite"}}/><span style={{fontSize:10,fontFamily:M,color:C.t3}}>LIVE</span>
      <div style={{position:"relative",marginLeft:8}}><div onClick={()=>setShowMenu(p=>!p)} style={{cursor:"pointer",display:"flex",alignItems:"center",gap:6}}>{profile?.avatar_url?<img src={profile.avatar_url} style={{width:28,height:28,borderRadius:99}} alt=""/>:<div style={{width:28,height:28,borderRadius:99,background:C.acc+"22",color:C.acc,display:"flex",alignItems:"center",justifyContent:"center",fontSize:12,fontWeight:700}}>{(profile?.name||"U")[0]}</div>}<svg width="12" height="12" fill="none" stroke={C.t3} strokeWidth="2" viewBox="0 0 24 24"><path d="M6 9l6 6 6-6"/></svg></div>
        {showMenu&&<><div style={{position:"fixed",inset:0,zIndex:99}} onClick={()=>setShowMenu(false)}/><div style={{position:"absolute",right:0,top:40,background:C.c1,border:`1px solid ${C.br}`,borderRadius:12,padding:8,minWidth:200,zIndex:100,animation:"up .15s ease",boxShadow:"0 8px 30px rgba(0,0,0,.5)"}}><div style={{padding:"10px 12px",borderBottom:`1px solid ${C.br}`,marginBottom:6}}><div style={{fontSize:14,fontWeight:600,color:C.t1}}>{profile?.name}</div><div style={{fontSize:11,color:C.t3,marginTop:2}}>{profile?.email}</div></div><button onClick={()=>{setTab("vault");setShowMenu(false);}} style={{width:"100%",padding:"9px 12px",background:"transparent",border:"none",color:C.t1,fontSize:13,textAlign:"left",cursor:"pointer",borderRadius:6}}>👤 Profile</button><button onClick={()=>{setOnboarding(true);setShowMenu(false);}} style={{width:"100%",padding:"9px 12px",background:"transparent",border:"none",color:C.t1,fontSize:13,textAlign:"left",cursor:"pointer",borderRadius:6}}>✏️ Edit</button><div style={{borderTop:`1px solid ${C.br}`,margin:"6px 0"}}/><button onClick={async()=>{setShowMenu(false);await sb.auth.signOut();setUser(null);setProfile(null);setJobs([]);setQA([]);setApplied([]);setAppliedJobs([]);}} style={{width:"100%",padding:"9px 12px",background:"transparent",border:"none",color:C.red,fontSize:13,textAlign:"left",cursor:"pointer",borderRadius:6,fontWeight:600}}>↩ Sign out</button></div></>}
      </div>
    </div>
    {/* Nav */}
    <div style={{display:"flex",borderBottom:`1px solid ${C.br}`,background:C.c1}}>{nav.map(n=><button key={n.id} onClick={()=>setTab(n.id)} style={{flex:1,padding:"10px 4px",display:"flex",flexDirection:"column",alignItems:"center",gap:2,border:"none",background:tab===n.id?C.bg:"transparent",borderBottom:tab===n.id?`2px solid ${C.acc}`:`2px solid transparent`,color:tab===n.id?C.acc:C.t3,cursor:"pointer",fontSize:10,fontWeight:700,fontFamily:M}}><span style={{fontSize:16}}>{n.ico}</span>{n.l}</button>)}</div>
    <div style={{maxWidth:660,margin:"0 auto",padding:"16px 16px 60px"}}>
      {tab==="hunt"&&<><div style={{display:"flex",gap:8,marginBottom:10}}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search..." onKeyDown={e=>e.key==="Enter"&&doSearch()} style={{flex:1,fontSize:15,padding:"13px 16px"}}/><button onClick={doSearch} disabled={loading} style={{padding:"0 22px",background:loading?C.c2:C.grad,color:loading?C.t3:"#fff",border:"none",borderRadius:8,fontSize:14,fontWeight:800,cursor:loading?"wait":"pointer"}}>HUNT</button></div><div style={{display:"flex",gap:6,flexWrap:"wrap",marginBottom:8}}>{QUICK.map(p=><Chip key={p} active={search===p} onClick={()=>setSearch(p)}>{p}</Chip>)}</div><div style={{display:"flex",gap:6,flexWrap:"wrap",marginBottom:8}}>{CATS.map(c=><Chip key={c} active={cat===c} color={C.pur} onClick={()=>setCat(c)}>{c}</Chip>)}</div><div style={{display:"flex",gap:6,flexWrap:"wrap",marginBottom:8,alignItems:"center"}}><span style={{fontSize:10,fontFamily:M,color:C.t3}}>REGION:</span>{Object.entries(FLAGS).filter(([k])=>k!=="other").map(([cc,f])=><Chip key={cc} active={selCountries.includes(cc)} color={C.blu} onClick={()=>setSelCountries(p=>p.includes(cc)?p.filter(c=>c!==cc):[...p,cc])}>{f} {cc.toUpperCase()}</Chip>)}</div><div style={{display:"flex",gap:8,marginBottom:12}}><button onClick={()=>setRemoteOnly(p=>!p)} style={{padding:"5px 16px",fontSize:12,border:`1px solid ${remoteOnly?C.grn+"55":C.br}`,borderRadius:99,background:remoteOnly?C.grn+"15":"transparent",color:remoteOnly?C.grn:C.t3,cursor:"pointer",fontWeight:600,fontFamily:M}}>🌍 Remote{remoteOnly&&" ✓"}</button>{(selCountries.length>0||remoteOnly)&&<button onClick={()=>{setSelCountries([]);setRemoteOnly(false);}} style={{padding:"5px 12px",fontSize:11,border:`1px solid ${C.br}`,borderRadius:99,background:"transparent",color:C.t3,cursor:"pointer"}}>Clear</button>}</div>{loading&&<ScanBar/>}{status&&<p style={{fontSize:11,fontFamily:M,color:C.t3,margin:"0 0 12px"}}>{status} · {filtered.length} showing</p>}<div style={{display:"flex",flexDirection:"column",gap:12}}>{filtered.map(j=><JobCard key={j.id} job={j} applied={applied.includes(j.id)} onApply={setApplyM} onMatch={setMatchM}/>)}</div></>}
      {tab==="tracked"&&<><div style={{fontSize:10,fontFamily:M,letterSpacing:2,color:C.acc,marginBottom:6}}>APPLICATIONS</div><h2 style={{color:C.t1,fontSize:24,fontWeight:800,marginBottom:20}}>{appliedJobs.length} tracked</h2>{appliedJobs.map((j,i)=><div key={i} style={{background:C.c1,border:`1px solid ${C.br}`,borderRadius:14,padding:16,marginBottom:10,display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><p style={{fontSize:15,fontWeight:700,color:C.t1}}>{j.title}</p><p style={{fontSize:13,color:C.t2,marginTop:3}}>{j.company} · {j.location}</p><p style={{fontSize:10,color:C.t3,fontFamily:M,marginTop:4}}>{new Date(j.applied_at).toLocaleDateString()} via {j.source}</p></div><div style={{display:"flex",gap:6,alignItems:"center"}}>{j.status==="queued"&&<span style={{fontSize:10,fontFamily:M,padding:"2px 8px",borderRadius:99,background:C.acc+"22",color:C.acc}}>⏳ Queued</span>}{j.status==="submitted"&&<span style={{fontSize:10,fontFamily:M,padding:"2px 8px",borderRadius:99,background:C.grn+"22",color:C.grn}}>✅ Done</span>}{j.status==="failed"&&<span style={{fontSize:10,fontFamily:M,padding:"2px 8px",borderRadius:99,background:C.red+"22",color:C.red}}>❌ Failed</span>}{j.status==="applied"&&<span style={{fontSize:10,fontFamily:M,padding:"2px 8px",borderRadius:99,background:C.t3+"22",color:C.t3}}>📋 Manual</span>}<a href={j.url} target="_blank" rel="noreferrer" style={{color:C.blu}}>↗</a></div></div>)}{!appliedJobs.length&&<p style={{color:C.t3}}>Apply from Hunt tab.</p>}</>}
      {tab==="vault"&&<><div style={{fontSize:10,fontFamily:M,letterSpacing:2,color:C.acc,marginBottom:6}}>VAULT</div><h2 style={{color:C.t1,fontSize:24,fontWeight:800,marginBottom:4}}>Profile & resume</h2><div style={{background:C.c1,border:`1px solid ${profile?.resume_url?C.grn+"44":C.br}`,borderRadius:14,padding:18,margin:"16px 0"}}><div style={{fontSize:10,fontFamily:M,letterSpacing:2,color:profile?.resume_url?C.grn:C.acc,marginBottom:10}}>{profile?.resume_url?"✓ RESUME":"📄 UPLOAD RESUME"}</div><p style={{color:C.t3,fontSize:12,marginBottom:10}}>Required for Auto Apply.</p><input type="file" accept=".pdf,.doc,.docx" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;const u=await db.uploadResume(f);if(u)setProfile(p=>({...p,resume_url:u}));}} style={{fontSize:13}}/>{profile?.resume_url&&<p style={{fontSize:11,color:C.grn,marginTop:8,fontFamily:M}}>✓ {profile.resume_url.split("/").pop()}</p>}</div><div style={{background:C.c1,border:`1px solid ${C.br}`,borderRadius:14,padding:18,marginBottom:20}}><div style={{fontSize:10,fontFamily:M,letterSpacing:2,color:C.t3,marginBottom:12}}>PROFILE</div>{profile&&Object.entries(profile).filter(([k,v])=>v&&!["id","created_at","updated_at","avatar_url","email","resume_url"].includes(k)).map(([k,v])=><div key={k} style={{marginBottom:10}}><label style={{fontSize:10,fontFamily:M,color:C.t3,textTransform:"uppercase"}}>{k.replace(/_/g," ")}</label><input value={v} onChange={e=>{setProfile(p=>({...p,[k]:e.target.value}));db.saveProfile({[k]:e.target.value});}} style={{marginTop:3}}/></div>)}</div><div style={{fontSize:10,fontFamily:M,letterSpacing:2,color:C.pur,marginBottom:10}}>SAVED Q&A ({qa.length})</div>{qa.map(q=><div key={q.id} style={{background:C.c1,border:`1px solid ${C.br}`,borderRadius:10,padding:14,marginBottom:8,display:"flex",justifyContent:"space-between"}}><div><p style={{fontSize:12,fontWeight:600,color:C.t2}}>{q.question}</p><p style={{fontSize:14,color:C.acc,marginTop:4}}>{q.answer}</p></div><button onClick={async()=>{await db.deleteQA(q.id);setQA(p=>p.filter(x=>x.id!==q.id));}} style={{background:"none",border:"none",color:C.red,cursor:"pointer",opacity:.6}}>×</button></div>)}</>}
      {tab==="ai"&&<><div style={{fontSize:10,fontFamily:M,letterSpacing:2,color:C.pur,marginBottom:6}}>AI LAB</div><h2 style={{color:C.t1,fontSize:24,fontWeight:800,marginBottom:20}}>Career intelligence</h2><div style={{display:"flex",gap:8,flexWrap:"wrap",marginBottom:16}}>{[{l:"📝 Resume",p:"Professional summary."},{l:"🎯 Interview",p:"5 interview questions."},{l:"💰 Salary",p:"Market rate?"},{l:"✉️ Outreach",p:"LinkedIn message."}].map(p=><Chip key={p.l} color={C.pur} onClick={()=>{setAiQ(p.p);(async()=>{setAiLd(true);setAiR((await db.callAI({type:"chat",prompt:p.p,profile}))?.text||"AI unavailable.");setAiLd(false);})();}}>{p.l}</Chip>)}</div><textarea value={aiQ} onChange={e=>setAiQ(e.target.value)} placeholder="Ask anything..." rows={3} style={{marginBottom:8,resize:"vertical",lineHeight:1.6}}/><button onClick={async()=>{setAiLd(true);setAiR((await db.callAI({type:"chat",prompt:aiQ,profile}))?.text||"AI unavailable.");setAiLd(false);}} disabled={aiLd||!aiQ} style={{width:"100%",padding:14,background:aiLd?C.c2:C.grad,color:aiLd?C.t3:"#fff",border:"none",borderRadius:10,fontWeight:700,cursor:aiLd?"wait":"pointer"}}>{aiLd?"Thinking...":"⚡ Run"}</button>{aiR&&<div style={{marginTop:16,background:C.c1,border:`1px solid ${C.br}`,borderRadius:14,padding:18,whiteSpace:"pre-wrap",fontSize:13,lineHeight:1.8,color:C.t2}}>{aiR}</div>}</>}
    </div>
    {applyM&&<ApplyModal job={applyM} profile={profile} onClose={()=>setApplyM(null)} onApply={handleApply}/>}
    {matchM&&<MatchModal job={matchM} profile={profile} onClose={()=>setMatchM(null)}/>}
  </div>;
}